clear;
load ../Step2_Data.mat;

SheetSize=200.0;
% CreateRec=[10,10,740,480];
CreateRec=[10,20,740,558];
%%
T0_Blank=['\n \n# Generate Sketch \n'];
T1_Sheet=['s = mdb.models[' char(39) 'Model-1' char(39) ...
    '].ConstrainedSketch(name=' char(39) '__profile__' ...
    char(39) ', sheetSize=%8.4e) \n'];

T2_GeometryText=['g, v, d, c = s.geometry, ' ...
    's.vertices, s.dimensions, s.constraints \n'];
T2_PrimaryText='s.setPrimaryObject(option=STANDALONE) \n';

T3_CreateRec=['s.rectangle(point1=(%8.4e, %8.4e), ' ...
    'point2=(%8.4e, %8.4e)) \n']; % CreateRec 1 2 3 4

T4_Setup={['p = mdb.models[' char(39) 'Model-1' char(39) ...
    '].Part(name=' char(39) 'Part-Base' char(39) ...
    ', dimensionality=THREE_D, type=DEFORMABLE_BODY) \n'];...
    ['p = mdb.models[' char(39) 'Model-1' char(39) ...
    '].parts[' char(39) 'Part-Base' char(39) '] \n'];...
    ['p.BaseShell(sketch=s) \n'];...
    ['s.unsetPrimaryObject() \n'];...
    ['p = mdb.models[' char(39) 'Model-1' char(39) ...
    '].parts[' char(39) 'Part-Base' char(39) '] \n'];...
    ['del mdb.models[' char(39) 'Model-1' char(39) ...
    '].sketches[' char(39) '__profile__' char(39) '] \n'];...
    ['p = mdb.models[' char(39) 'Model-1' char(39) ...
    '].parts[' char(39) 'Part-Base' char(39) '] \n'];...
    ['f, e, d1 = p.faces, p.edges, p.datums \n'];
    };


%%
OutputFileName='WTest0.py';
fileID = fopen(OutputFileName,'a+');

fprintf(fileID,T0_Blank);
fprintf(fileID,T1_Sheet,SheetSize);
fprintf(fileID,T2_GeometryText);
fprintf(fileID,T2_PrimaryText);

fprintf(fileID,T3_CreateRec,CreateRec(1),CreateRec(2),...
    CreateRec(3),CreateRec(4));

% -------
for n1=1:length(T4_Setup)
    fprintf(fileID,T4_Setup{n1});
end

%--------
fclose(fileID);

save Write1_Dat;